---
# tasks file for gh_cli

#Install GitHub CLI
- name: Add GitHub CLI GPG apt Key
  apt_key:
     url: https://cli.github.com/packages/githubcli-archive-keyring.gpg
     state: present

- name: Add GitHub CLI Repository
  apt_repository:
    repo: deb https://cli.github.com/packages stable main
    state: present

- name: Update apt and install gh
  apt:
    name:
      - gh
    state: latest
    update_cache: true
