---
# tasks file for docker-install

#Update apt and install system packages
    - name: Update apt and install required system packages
      apt:
        pkg:
          - python3-pip
          - virtualenv
        state: latest
        update_cache: true

#Install Docker
    - name: Add Docker GPG apt Key
      apt_key:
        url: https://download.docker.com/linux/ubuntu/gpg
        state: present

    - name: Add Docker Repository
      apt_repository:
        repo: deb https://download.docker.com/linux/ubuntu jammy stable
        state: present

    - name: Update apt and install docker-ce
      apt:
        name:
          - docker-ce
          - docker-ce-cli
          - containerd.io
          - docker-buildx-plugin
          - docker-compose-plugin
        state: latest
        update_cache: true

    - name: Install Docker Module for Python
      pip:
        name: docker

    - name: Add "{{ alter_user }}" user to "docker" group
      user:
        name: "{{ alter_user }}"
        groups: "docker"
        append: yes

#Install Docker Compse
    - name: Install docker-compose
      get_url:
        url: https://github.com/docker/compose/releases/download/v2.21.0/docker-compose-linux-x86_64
        dest: /usr/local/bin/docker-compose
        mode: '755'
